import type { ModelCapability } from "@semafore/router";

// A small fixture catalog used by every example. In a real app you would
// usually pull this from models.dev via ModelsDevCapabilityCatalog instead.
export const exampleCatalog: readonly ModelCapability[] = [
  {
    providerId: "google",
    providerName: "Google",
    modelId: "gemini-2.5-flash",
    modelName: "Gemini 2.5 Flash",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    features: ["structured_output", "tools", "attachments", "web_search"],
    limits: { contextTokens: 1_000_000, outputTokens: 65_000 },
    pricing: { inputPerMillionTokens: 0.3, outputPerMillionTokens: 2.5 },
    latencyClass: "fast",
    qualityScore: 7,
  },
  {
    providerId: "anthropic",
    providerName: "Anthropic",
    modelId: "claude-haiku-4-5",
    modelName: "Claude Haiku 4.5",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    features: ["structured_output", "tools", "attachments"],
    limits: { contextTokens: 200_000, outputTokens: 64_000 },
    pricing: { inputPerMillionTokens: 1, outputPerMillionTokens: 5 },
    latencyClass: "fast",
    qualityScore: 7.5,
  },
  {
    providerId: "anthropic",
    providerName: "Anthropic",
    modelId: "claude-opus-4-8",
    modelName: "Claude Opus 4.8",
    inputModalities: ["text", "image", "pdf"],
    outputModalities: ["text"],
    features: ["structured_output", "tools", "reasoning", "attachments"],
    limits: { contextTokens: 200_000, outputTokens: 32_000 },
    pricing: { inputPerMillionTokens: 15, outputPerMillionTokens: 75 },
    latencyClass: "slow",
    qualityScore: 10,
  },
  {
    providerId: "openai",
    providerName: "OpenAI",
    modelId: "gpt-4o",
    modelName: "GPT-4o",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    features: ["structured_output", "tools", "attachments", "web_search"],
    limits: { contextTokens: 128_000, outputTokens: 16_000 },
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 10 },
    latencyClass: "standard",
    qualityScore: 8,
  },
  {
    providerId: "mistral",
    providerName: "Mistral (EU)",
    modelId: "mistral-large",
    modelName: "Mistral Large",
    inputModalities: ["text"],
    outputModalities: ["text"],
    features: ["structured_output", "tools"],
    limits: { contextTokens: 128_000, outputTokens: 16_000 },
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 6 },
    latencyClass: "standard",
    qualityScore: 7,
  },
  {
    providerId: "local",
    providerName: "Local (Ollama)",
    modelId: "llama-3.3-70b",
    modelName: "Llama 3.3 70B",
    inputModalities: ["text"],
    outputModalities: ["text"],
    features: ["tools"],
    limits: { contextTokens: 128_000, outputTokens: 8_000 },
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    latencyClass: "standard",
    qualityScore: 6,
  },
];
